#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INN_CSHARP
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MG_inkjop")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertfarm(farm instance);
    partial void Updatefarm(farm instance);
    partial void Deletefarm(farm instance);
    partial void Insertflower(flower instance);
    partial void Updateflower(flower instance);
    partial void Deleteflower(flower instance);
    partial void Insertlengths(lengths instance);
    partial void Updatelengths(lengths instance);
    partial void Deletelengths(lengths instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::INN_CSHARP.Properties.Settings.Default.MG_inkjopConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<farm> farms
		{
			get
			{
				return this.GetTable<farm>();
			}
		}
		
		public System.Data.Linq.Table<flower> flowers
		{
			get
			{
				return this.GetTable<flower>();
			}
		}
		
		public System.Data.Linq.Table<lengths> lengths
		{
			get
			{
				return this.GetTable<lengths>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.farms")]
	public partial class farm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _farm_id;
		
		private string _farm_name;
		
		private string _farm_code;
		
		private EntitySet<flower> _flowers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfarm_idChanging(int value);
    partial void Onfarm_idChanged();
    partial void Onfarm_nameChanging(string value);
    partial void Onfarm_nameChanged();
    partial void Onfarm_codeChanging(string value);
    partial void Onfarm_codeChanged();
    #endregion
		
		public farm()
		{
			this._flowers = new EntitySet<flower>(new Action<flower>(this.attach_flowers), new Action<flower>(this.detach_flowers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_farm_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int farm_id
		{
			get
			{
				return this._farm_id;
			}
			set
			{
				if ((this._farm_id != value))
				{
					this.Onfarm_idChanging(value);
					this.SendPropertyChanging();
					this._farm_id = value;
					this.SendPropertyChanged("farm_id");
					this.Onfarm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_farm_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string farm_name
		{
			get
			{
				return this._farm_name;
			}
			set
			{
				if ((this._farm_name != value))
				{
					this.Onfarm_nameChanging(value);
					this.SendPropertyChanging();
					this._farm_name = value;
					this.SendPropertyChanged("farm_name");
					this.Onfarm_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_farm_code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string farm_code
		{
			get
			{
				return this._farm_code;
			}
			set
			{
				if ((this._farm_code != value))
				{
					this.Onfarm_codeChanging(value);
					this.SendPropertyChanging();
					this._farm_code = value;
					this.SendPropertyChanged("farm_code");
					this.Onfarm_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="farm_flower", Storage="_flowers", ThisKey="farm_id", OtherKey="farm_id")]
		public EntitySet<flower> flowers
		{
			get
			{
				return this._flowers;
			}
			set
			{
				this._flowers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_flowers(flower entity)
		{
			this.SendPropertyChanging();
			entity.farm = this;
		}
		
		private void detach_flowers(flower entity)
		{
			this.SendPropertyChanging();
			entity.farm = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flowers")]
	public partial class flower : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fl_id;
		
		private string _variety;
		
		private string _colour;
		
		private string _plu;
		
		private int _farm_id;
		
		private string _barcode;
		
		private bool _mix;
		
		private string _sticker_text;
		
		private int _length_id;
		
		private short _bucket_size;
		
		private string _sleeve_type;
		
		private decimal _fob;
		
		private decimal _price_pr_bunch;
		
		private bool _fairtrade;
		
		private short _bunch_pr_box;
		
		private byte _bunch_pr_bucket;
		
		private byte _stems_pr_bunch;
		
		private int _pak_rate;
		
		private EntityRef<farm> _farm;
		
		private EntityRef<lengths> _lengths;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfl_idChanging(int value);
    partial void Onfl_idChanged();
    partial void OnvarietyChanging(string value);
    partial void OnvarietyChanged();
    partial void OncolourChanging(string value);
    partial void OncolourChanged();
    partial void OnpluChanging(string value);
    partial void OnpluChanged();
    partial void Onfarm_idChanging(int value);
    partial void Onfarm_idChanged();
    partial void OnbarcodeChanging(string value);
    partial void OnbarcodeChanged();
    partial void OnmixChanging(bool value);
    partial void OnmixChanged();
    partial void Onsticker_textChanging(string value);
    partial void Onsticker_textChanged();
    partial void Onlength_idChanging(int value);
    partial void Onlength_idChanged();
    partial void Onbucket_sizeChanging(short value);
    partial void Onbucket_sizeChanged();
    partial void Onsleeve_typeChanging(string value);
    partial void Onsleeve_typeChanged();
    partial void OnfobChanging(decimal value);
    partial void OnfobChanged();
    partial void Onprice_pr_bunchChanging(decimal value);
    partial void Onprice_pr_bunchChanged();
    partial void OnfairtradeChanging(bool value);
    partial void OnfairtradeChanged();
    partial void Onbunch_pr_boxChanging(short value);
    partial void Onbunch_pr_boxChanged();
    partial void Onbunch_pr_bucketChanging(byte value);
    partial void Onbunch_pr_bucketChanged();
    partial void Onstems_pr_bunchChanging(byte value);
    partial void Onstems_pr_bunchChanged();
    partial void Onpak_rateChanging(int value);
    partial void Onpak_rateChanged();
    #endregion
		
		public flower()
		{
			this._farm = default(EntityRef<farm>);
			this._lengths = default(EntityRef<lengths>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fl_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fl_id
		{
			get
			{
				return this._fl_id;
			}
			set
			{
				if ((this._fl_id != value))
				{
					this.Onfl_idChanging(value);
					this.SendPropertyChanging();
					this._fl_id = value;
					this.SendPropertyChanged("fl_id");
					this.Onfl_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_variety", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string variety
		{
			get
			{
				return this._variety;
			}
			set
			{
				if ((this._variety != value))
				{
					this.OnvarietyChanging(value);
					this.SendPropertyChanging();
					this._variety = value;
					this.SendPropertyChanged("variety");
					this.OnvarietyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_colour", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string colour
		{
			get
			{
				return this._colour;
			}
			set
			{
				if ((this._colour != value))
				{
					this.OncolourChanging(value);
					this.SendPropertyChanging();
					this._colour = value;
					this.SendPropertyChanged("colour");
					this.OncolourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plu", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string plu
		{
			get
			{
				return this._plu;
			}
			set
			{
				if ((this._plu != value))
				{
					this.OnpluChanging(value);
					this.SendPropertyChanging();
					this._plu = value;
					this.SendPropertyChanged("plu");
					this.OnpluChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_farm_id", DbType="Int NOT NULL")]
		public int farm_id
		{
			get
			{
				return this._farm_id;
			}
			set
			{
				if ((this._farm_id != value))
				{
					if (this._farm.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfarm_idChanging(value);
					this.SendPropertyChanging();
					this._farm_id = value;
					this.SendPropertyChanged("farm_id");
					this.Onfarm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barcode", DbType="Char(14) NOT NULL", CanBeNull=false)]
		public string barcode
		{
			get
			{
				return this._barcode;
			}
			set
			{
				if ((this._barcode != value))
				{
					this.OnbarcodeChanging(value);
					this.SendPropertyChanging();
					this._barcode = value;
					this.SendPropertyChanged("barcode");
					this.OnbarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mix", DbType="Bit NOT NULL")]
		public bool mix
		{
			get
			{
				return this._mix;
			}
			set
			{
				if ((this._mix != value))
				{
					this.OnmixChanging(value);
					this.SendPropertyChanging();
					this._mix = value;
					this.SendPropertyChanged("mix");
					this.OnmixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sticker_text", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sticker_text
		{
			get
			{
				return this._sticker_text;
			}
			set
			{
				if ((this._sticker_text != value))
				{
					this.Onsticker_textChanging(value);
					this.SendPropertyChanging();
					this._sticker_text = value;
					this.SendPropertyChanged("sticker_text");
					this.Onsticker_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_length_id", DbType="Int NOT NULL")]
		public int length_id
		{
			get
			{
				return this._length_id;
			}
			set
			{
				if ((this._length_id != value))
				{
					if (this._lengths.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlength_idChanging(value);
					this.SendPropertyChanging();
					this._length_id = value;
					this.SendPropertyChanged("length_id");
					this.Onlength_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bucket_size", DbType="SmallInt NOT NULL")]
		public short bucket_size
		{
			get
			{
				return this._bucket_size;
			}
			set
			{
				if ((this._bucket_size != value))
				{
					this.Onbucket_sizeChanging(value);
					this.SendPropertyChanging();
					this._bucket_size = value;
					this.SendPropertyChanged("bucket_size");
					this.Onbucket_sizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sleeve_type", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sleeve_type
		{
			get
			{
				return this._sleeve_type;
			}
			set
			{
				if ((this._sleeve_type != value))
				{
					this.Onsleeve_typeChanging(value);
					this.SendPropertyChanging();
					this._sleeve_type = value;
					this.SendPropertyChanged("sleeve_type");
					this.Onsleeve_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fob", DbType="Decimal(18,2) NOT NULL")]
		public decimal fob
		{
			get
			{
				return this._fob;
			}
			set
			{
				if ((this._fob != value))
				{
					this.OnfobChanging(value);
					this.SendPropertyChanging();
					this._fob = value;
					this.SendPropertyChanged("fob");
					this.OnfobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_pr_bunch", DbType="Decimal(18,2) NOT NULL")]
		public decimal price_pr_bunch
		{
			get
			{
				return this._price_pr_bunch;
			}
			set
			{
				if ((this._price_pr_bunch != value))
				{
					this.Onprice_pr_bunchChanging(value);
					this.SendPropertyChanging();
					this._price_pr_bunch = value;
					this.SendPropertyChanged("price_pr_bunch");
					this.Onprice_pr_bunchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fairtrade", DbType="Bit NOT NULL")]
		public bool fairtrade
		{
			get
			{
				return this._fairtrade;
			}
			set
			{
				if ((this._fairtrade != value))
				{
					this.OnfairtradeChanging(value);
					this.SendPropertyChanging();
					this._fairtrade = value;
					this.SendPropertyChanged("fairtrade");
					this.OnfairtradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bunch_pr_box", DbType="SmallInt NOT NULL")]
		public short bunch_pr_box
		{
			get
			{
				return this._bunch_pr_box;
			}
			set
			{
				if ((this._bunch_pr_box != value))
				{
					this.Onbunch_pr_boxChanging(value);
					this.SendPropertyChanging();
					this._bunch_pr_box = value;
					this.SendPropertyChanged("bunch_pr_box");
					this.Onbunch_pr_boxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bunch_pr_bucket", DbType="TinyInt NOT NULL")]
		public byte bunch_pr_bucket
		{
			get
			{
				return this._bunch_pr_bucket;
			}
			set
			{
				if ((this._bunch_pr_bucket != value))
				{
					this.Onbunch_pr_bucketChanging(value);
					this.SendPropertyChanging();
					this._bunch_pr_bucket = value;
					this.SendPropertyChanged("bunch_pr_bucket");
					this.Onbunch_pr_bucketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stems_pr_bunch", DbType="TinyInt NOT NULL")]
		public byte stems_pr_bunch
		{
			get
			{
				return this._stems_pr_bunch;
			}
			set
			{
				if ((this._stems_pr_bunch != value))
				{
					this.Onstems_pr_bunchChanging(value);
					this.SendPropertyChanging();
					this._stems_pr_bunch = value;
					this.SendPropertyChanged("stems_pr_bunch");
					this.Onstems_pr_bunchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pak_rate", DbType="Int NOT NULL")]
		public int pak_rate
		{
			get
			{
				return this._pak_rate;
			}
			set
			{
				if ((this._pak_rate != value))
				{
					this.Onpak_rateChanging(value);
					this.SendPropertyChanging();
					this._pak_rate = value;
					this.SendPropertyChanged("pak_rate");
					this.Onpak_rateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="farm_flower", Storage="_farm", ThisKey="farm_id", OtherKey="farm_id", IsForeignKey=true)]
		public farm farm
		{
			get
			{
				return this._farm.Entity;
			}
			set
			{
				farm previousValue = this._farm.Entity;
				if (((previousValue != value) 
							|| (this._farm.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._farm.Entity = null;
						previousValue.flowers.Remove(this);
					}
					this._farm.Entity = value;
					if ((value != null))
					{
						value.flowers.Add(this);
						this._farm_id = value.farm_id;
					}
					else
					{
						this._farm_id = default(int);
					}
					this.SendPropertyChanged("farm");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="length_flower", Storage="_lengths", ThisKey="length_id", OtherKey="length_id", IsForeignKey=true)]
		public lengths lengths
		{
			get
			{
				return this._lengths.Entity;
			}
			set
			{
				lengths previousValue = this._lengths.Entity;
				if (((previousValue != value) 
							|| (this._lengths.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._lengths.Entity = null;
						previousValue.flowers.Remove(this);
					}
					this._lengths.Entity = value;
					if ((value != null))
					{
						value.flowers.Add(this);
						this._length_id = value.length_id;
					}
					else
					{
						this._length_id = default(int);
					}
					this.SendPropertyChanged("lengths");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lengths")]
	public partial class lengths : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _length_id;
		
		private string _length1;
		
		private EntitySet<flower> _flowers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlength_idChanging(int value);
    partial void Onlength_idChanged();
    partial void Onlength1Changing(string value);
    partial void Onlength1Changed();
    #endregion
		
		public lengths()
		{
			this._flowers = new EntitySet<flower>(new Action<flower>(this.attach_flowers), new Action<flower>(this.detach_flowers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_length_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int length_id
		{
			get
			{
				return this._length_id;
			}
			set
			{
				if ((this._length_id != value))
				{
					this.Onlength_idChanging(value);
					this.SendPropertyChanging();
					this._length_id = value;
					this.SendPropertyChanged("length_id");
					this.Onlength_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="length", Storage="_length1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string length1
		{
			get
			{
				return this._length1;
			}
			set
			{
				if ((this._length1 != value))
				{
					this.Onlength1Changing(value);
					this.SendPropertyChanging();
					this._length1 = value;
					this.SendPropertyChanged("length1");
					this.Onlength1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="length_flower", Storage="_flowers", ThisKey="length_id", OtherKey="length_id")]
		public EntitySet<flower> flowers
		{
			get
			{
				return this._flowers;
			}
			set
			{
				this._flowers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_flowers(flower entity)
		{
			this.SendPropertyChanging();
			entity.lengths = this;
		}
		
		private void detach_flowers(flower entity)
		{
			this.SendPropertyChanging();
			entity.lengths = null;
		}
	}
}
#pragma warning restore 1591
